apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # Bu, kaç adet pod çalıştırılacağını belirler.
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: arifshn/portgres:latest  # Docker Hub'daki imaj adınızı buraya yazın
        ports:
        - containerPort: 80

